### ISSUE TITLE
Could you share your template?

### ISSUE THREAD

**Issue by anoriginalmoniker** [Joe-Moran/obsidian-quick-add-musicBrainz-macro#1]
Hi. I stumbled on your work after searching for a way to add albums to Obsidian. Would you mind sharing the template you use with this script?

**Comment by Joe-Moran** [comment]
@anoriginalmoniker [here ](https://github.com/Joe-Moran/obsidian-quick-add-musicBrainz-macro/blob/master/Add%20Album%20Template.md) it is! Hope you find this helpful!

**Comment by anoriginalmoniker** [comment]
Thanks a lot!
